### ISSUE TITLE
EVM burn (send to 0x0) fails

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#1997]
trying this SC fails on execution of `burn`:
```
contract Burn {

    address burnAddress= address(0x0);

    constructor() {
    }

    function burn() external payable {
        (bool result, ) = burnAddress.call{value: msg.value}("");
        require(result,"Failed to burn");
    }

}
```
unfortunatly the errormessage is not giving any details (and is also not in the format that remix would expect).

(sidenote: how to best report errors for evm? here as issues, or somehow different?)

**Comment by shohamc1** [comment]
I deployed this contract on Sepolia (used compiler 0.8.18) and the function fails there as well ([link](https://sepolia.etherscan.io/tx/0xb4ca9ea90a2cd0ca58aa35d420affa7938b625430acf9583010d41352294b625)). Maybe there is an issue with the contract itself.

> unfortunatly the errormessage is not giving any details (and is also not in the format that remix would expect).

This does seem to be a bug, can you share what the output/error on Remix is?

> (sidenote: how to best report errors for evm? here as issues, or somehow different?)

Creating an issue on this repo with the `evm` and `bug` labels would be best way!

**Comment by shohamc1** [comment]
Update: I was able to deploy and interact with the contract with no errors.

TX hash for burning 2 DFI: `0x1c4e884571f20417a67b837815f14d9a25e512f036686ec439f42bfd479c000d`

Checking balance of `0x0000000000000000000000000000000000000000`
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBalance","params": ["0x0000000000000000000000000000000000000000"],"id":31}' localhost:20551
{"jsonrpc":"2.0","result":"0x1bc16d674ec80000","id":31}
```

**Comment by kuegi** [comment]
Thx for the infos. What would be a good reference to check against? I was checking with the Remix VM (Shanghai). 

I am still not able to interact successfully with the SC via remix.

regarding the error, I get
```
transact to Burn.burn errored: Returned error: {"jsonrpc":"2.0","error":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":-32001,\"message\":\"Custom error: Could not publish raw transaction: 0xf871188502540be40082808d9414b6dc5dae34bfc7bef1f97e07f124eedfdf00d2872386f26fc100008444df8e708208fba01a4fe090bcf8ba7c9e128a298dd8d0d586989948d1ea27f69f982e6eb5b6e87ea07a7b5eb102dde1770e64cb214fd29ccaf37d290f4f84de69b09b33840ed7ac2d\"}}}'","id":2087613538176009}

```
so its really hard to debug/trace errors.

This seems to be a standard error and the node does not even accept it to the mempool. (AFAIU it should always get into the chain, just as a failed tx)

**Comment by shohamc1** [comment]
Just ran your raw transaction, and it fails with this error: `evm_validate_raw_tx fails with error: Error calling EVM Error(OutOfGas)`. Maybe try increasing the gas limit manually and retrying?

> so its really hard to debug/trace errors

Right now the way to debug the transactions is to run your own node with the `RUST_LOG=debug` flag to see execution logs. But this is a bug, the execution failure should be returned instead of the generic failure message you see right now.

> What would be a good reference to check against?

Really any other EVM testnet. Remix VM works well, but I personally prefer Sepolia testnet.

> This seems to be a standard error and the node does not even accept it to the mempool. (AFAIU it should always get into the chain, just as a failed tx)

Sounds correct to me, and it's a bug with the current RPC implementation. The miner itself will include failed transactions in the mempool currently. Will need some fixing, thanks for reporting it.

**Comment by shohamc1** [comment]
As of https://github.com/DeFiCh/ain/pull/2003, the RPC will no longer check execution results when sending a transaction.

**Comment by kuegi** [comment]
connected to floppynet node of mydefichain, and can confirm that SC works with more gas, and failing (not enough gas) tx is now accepted but then fails in the chain (as it should).
closing this.

please reopen if you want it for the missing error/debug message on the failed tx.

**Comment by kuegi** [comment]
last questions @shohamc1 : where can I set `RUST_LOG=debug` ? got the evm node running, but not sure how to set that? for compilation or on execution?

**Comment by Jouzo** [comment]
You can set it on execution with `RUST_LOG=debug defid`

**Comment by Jouzo** [comment]
https://github.com/DeFiCh/ain/pull/2012 Should help make the RPC returned error clearer
